In [3]:
import numpy as np
x = np.array([0,1,2,3,4,5])
print(x)

[0 1 2 3 4 5]


In [48]:
import numpy as np
x = np.array([[0,1],[2,3]])
y = [[0,1],[2,3]]
print(x)
print("------------------------")
print(y)

[[0 1]
 [2 3]]
------------------------
[[0, 1], [2, 3]]


In [12]:
import numpy as np
x = np.array([0,1,2,3,4,5])
print(x[3]) #หาตำเเหน่งที่ 4 (0 1 2 3)

3


In [14]:
import numpy as np
x = np.array([[0,1,2],[3,4,5]])
print(x[0][2]) #[วงเล็บ 1][ข้อมูลตัวที่ 3 ในวงเล็ก 1]


2


In [15]:
import numpy as np
x = np.array([[0,1,2],[3,4,5]])
print(x[0,2]) #[วงเล็บ 1,ข้อมูลตัวที่ 3 ในวงเล็ก 1]

2


In [20]:
import numpy as np
x = np.array([[[0,1,2,3],[4,5,6,7]]])
print(x[0,1,1]) #[วงเล็บใหญ่เเรก,วงเล็บ 2,ข้อมูลตัวที่ 2 ในวงเล็บ 2]

5


In [23]:
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([[0,1,2],[3,4,5]])
z = np.array([[[0,1,2,3],[4,5,6,7]]])
print(x.ndim) #บอกจำนวนมิติ 
print(y.ndim) 
print(z.ndim) 

1
2
3


In [49]:
import numpy as np
x = np.array([0,1,2,3,4,5])
print(x[0:3]) #เอาตำเเหน่งที่ 1 กับ 2
print("------------------------") 
print(x[2:4]) #เอาตำเเหน่งที่ 3 กับ 4

[0 1 2]
------------------------
[2 3]


In [47]:
import numpy as np
x = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
print(x[0,2:4]) #เอาวงเล็บ 1 ,ตำเเหน่งที่ 3 กับ 4 
print("------------------------")
print(x[1,2:4]) #เอาวงเล็บ 2 ,ตำเเหน่งที่ 3 กับ 4 

[2 3]
------------------------
[8 9]


In [46]:
import numpy as np
x = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
print(x.shape) #บอกว่าเเยกเป็น 2 วงเล็บ,ข้อมูล 6 ตัว
print("------------------------")
y = np.array([[0,1,2,3,4],[6,7,8,9,10]])
print(y.shape) #บอกว่าเเยกเป็น 2 วงเล็บ,ข้อมูล 5 ตัว

(2, 6)
------------------------
(2, 5)


In [45]:
import numpy as np
x = np.array([0,1,2,3,4,5])
print(x.reshape(2,3)) #เเยก 2 วงเล็บ,ข้อมูล 3 ตัว(ต้องลงตัว)
print("------------------------")
y = np.array([0,1,2,3,4,5])
print(y.reshape(3,2)) #เเยก 3 วงเล็บ,ข้อมูล 2 ตัว(ต้องลงตัว)

[[0 1 2]
 [3 4 5]]
------------------------
[[0 1]
 [2 3]
 [4 5]]


In [50]:
import numpy as np
x = np.array([0,1,2,3,4,5])
for i in range(len(x)):
    print(x[i])

0
1
2
3
4
5


In [53]:
import numpy as np
x = np.array([0,1,2,3,4,5])
for i in x: #x เเทนจำนวนในวงเล็บ
    print(i)

0
1
2
3
4
5


In [52]:
import numpy as np
x = np.array([0,1,2,3,4,5])
for i in x: #x เเทนจำนวนในวงเล็บ
    print("Hello")

Hello
Hello
Hello
Hello
Hello
Hello


In [60]:
import numpy as np
x = np.array([[0],[1],[2],[3],[4],[5]])
for i in x: #ถอดวงเล็บที่ 1
    print(i)

[0]
[1]
[2]
[3]
[4]
[5]


In [64]:
import numpy as np
array = np.array([[0],[1],[2],[3],[4],[5]])
for i in array: #ถอดวงเล็บที่ 1
    for a in i: #ถอดวงเล็บที่ 2
        print(a)

0
1
2
3
4
5
