In [1]:
import numpy as np
from numpy import random

In [3]:
a = random.randint(100, size = (3,5)) #สุ่มตัวเลข 100 ตัว, size = (วงเล็บ,จำนวนข้อมูล)
b = np.array([1,2,3,4,5,6])
print(a)

[[42 19  6 98  6]
 [93 36 45 35 81]
 [57 89 39 28 32]]


In [5]:
a = random.randint(0,2, size = (3,5)) #สุ่มตัวเลขตำเเหน่งที่ 0-2, size = (วงเล็บ,จำนวนข้อมูล)
b = np.array([1,2,3,4,5,6])
print(a)

[[1 1 1 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]
